#!/bin/bash

step=${BLOCK_INSTANCE:-5}

case ${1:-$BLOCK_BUTTON} in
inc | 4)
  [ ! -z "$2" ] && [ "$(ponymix get-volume)" -ge 50 ] && exit
  ponymix increase $step >/dev/null 2>&1
  pkill -RTMIN+1 i3blocks
  ;;
dec | 5)
  [ ! -z "$2" ] && [ "$(ponymix get-volume)" -le 20 ] && exit
  ponymix decrease $step >/dev/null 2>&1
  pkill -RTMIN+1 i3blocks
  ;;
mute | 3)
  ponymix toggle >/dev/null 2>&1
  pkill -RTMIN+1 i3blocks
  ;;
esac

vol="$(ponymix get-volume)"

if (($vol <= 20)); then
  icon=""
elif (($vol <= 35)); then
  icon=""
elif (($vol <= 50)); then
  icon=""
else
  icon=""
fi

echo "$icon $vol%"
echo "$vol"
ponymix is-muted && exit 33 || exit 0
