#!/usr/bin/env bash
# vim ft=bash

# use favs playlist or whole library
[[ "$(basename "$0")" == *_favourite* ]] && wsong="playlist Favorites" || wsong="listall"

# choose song from whole specifed location
songs=$(mpc -f '(%time%) %file%' $wsong | fzf --multi --reverse --border --preview="$HOME/dev/i3wmonarch/scripts/multimedia/get_song_info {}" | cut -d ' ' -f2-)
[ -z "$songs" ] && exit 1

# add the song to the current playlist
echo "$songs" | xargs -d '\n' -I{} mpc insert "{}"

# if we only want to queue next song
[[ "$(basename "$0")" == *_queue ]] && exit 0

# play the song
mpc next

