#!/bin/bash
# temp fix for stuck ncat
#pkill -f '^ncat -n -w 1 127.0.0.1 6600$'
mpcdata=$(echo -ne "status\ncurrentsong\nclose\n" | ncat -n -w 1 127.0.0.1 6600 2>/dev/null)
if [[ $? != 0 ]]; then
    exit
fi
case $BLOCK_BUTTON in
    # 1-2-3 left-middle-right mouse button
    1) ~/dev/i3wmonarch/scripts/multimedia/audioplayer_control toggle 2>/dev/null 1>&2;;
    2) ~/dev/i3wmonarch/scripts/multimedia/youtube_currentsong 2>/dev/null 1>&2 ;;
    3) ~/dev/i3wmonarch/scripts/multimedia/audioplayer_control next 2>/dev/null 1>&2;;
    4) ~/dev/i3wmonarch/scripts/multimedia/audioplayer_control seeki 2>/dev/null 1>&2;;
    5) ~/dev/i3wmonarch/scripts/multimedia/audioplayer_control seekd 2>/dev/null 1>&2;;
esac

curmode=$(echo "$mpcdata" | grep -E "^state:" | cut -d ' ' -f2-)
shortst=""
case $curmode in
    stop)
        shortst=" "
        ;;
    play)
        shortst=" "
        ;;
    pause)
        shortst=" "
        ;;
esac
echo -n "$shortst"
songtotal=$(echo "$mpcdata" | grep -E "^duration:" | head -n 1 | cut -d ' ' -f2- | cut -d '.' -f1)
songcurrent=$(echo "$mpcdata" | grep -E "^elapsed:" | cut -d ' ' -f2- | cut -d '.' -f1)

cursong="$(echo "$mpcdata" | grep -E "^Artist:" | cut -d ' ' -f2- | tr -d '\n')";
cursong="${cursong} - $(echo "$mpcdata" | grep -E "^Title:" | cut -d ' ' -f2- | tr -d '\n')";
cursong="${cursong} ( $(echo "$mpcdata" | grep -E "^Album:" | cut -d ' ' -f2- | tr -d '\n')";
cursong="${cursong} | $(echo "$mpcdata" | grep -E "^Date:" | cut -d ' ' -f2- | tr -d '\n') )";

[[ "$cursong" == " -  (  |  )" ]] && cursong=$(echo "$mpcdata" | grep -E "^file:" | cut -d ' ' -f2-)

if [ ! -z "$songtotal" ]; then
    songtimes=$(printf '%02d:%02d / %02d:%02d' $(($songcurrent/60)) $(($songcurrent%60)) $(($songtotal/60)) $(($songtotal%60)))
fi

# default value
maxlen=35
case "$(xdpyinfo | awk '/dimensions/{print $2}' |cut -d 'x' -f1)" in
"1920")maxlen=80;;
esac
maxlen="$((maxlen-${#songtimes}))"
curslen=${#cursong}

if [ "$curslen" -gt "$maxlen" ]; then
 delta=$((($(date +%-S))%($curslen-$maxlen+1)))
 cursong="${cursong:($delta):$maxlen}"
fi

printf "%${maxlen}s" "${cursong}"
echo -ne " ${songtimes}\n"

blink=$(($(date "+%-S")%8))
case "$blink" in
    0) colorrgb="#0BDD94";;
    1) colorrgb="#E16725";;
    2) colorrgb="#E5E913";;
    3) colorrgb="#008DFF";;
    4) colorrgb="#FF0041";;
    5) colorrgb="#22FEE0";;
    6) colorrgb="#E4E4E4";;
    7) colorrgb="#FFD59C";;
    *) colorrgb="#FFFFFF";;
esac
echo "$shortst"
echo "$colorrgb"
