#!/bin/bash
set -e

mpdi3dir="$HOME/dev/i3wmonarch/.mpd/store/playlists"
favsfile="${mpdi3dir}/Favorites.m3u"

# create playlist symlink if it does not exist
if [ ! -f "$favsfile" ]; then
    mkdir -pv "${mpdi3dir}"
    ln -s -v "$HOME/Dropbox/mpd/Favorites.m3u" "${favsfile}"
fi

# start mpd service
systemctl --user start mpd.service

get_con_id() {
    i3-msg -t get_tree | jq '..|.?|select(.nodes)|select(.window_properties.window_role)|select(.window_properties.window_role=="termaudioplayer")|.id'|head -n1
}
# start screen in terminal window or in current shell
if [ ! -z "$DISPLAY" ]; then
    # try to find existing player window
    if [ -z "$(get_con_id)" ]; then
        # create new player window
        exec xfce4-terminal -e 'screen  -x -R audioplayer -m ncmpcpp' --role termaudioplayer
    fi
    # focus the player window
    i3-msg "[con_id=\"$(get_con_id)\"] focus"
else
    screen  -x -R audioplayer -m ncmpcpp
fi

