#!/bin/bash
set -e

# start mpd service
systemctl --user start mpd.service

get_con_id() {
    i3-msg -t get_tree | jq '.. |.nodes? | select(. != null) | .[] | select(.window_properties.window_role=="termaudioplayer") | .id' |head -n1
}
# start screen in terminal window or in current shell
if [ ! -z "$DISPLAY" ]; then
    # try to find existing player window
    if [ -z "$(get_con_id)" ]; then
        # create new player window
        exec xfce4-terminal -e 'screen  -x -R audioplayer -m ncmpcpp' --role termaudioplayer
    fi
    # focus the player window
    i3-msg "[con_id=\"$(get_con_id)\"] focus"
else
    screen  -x -R audioplayer -m ncmpcpp
fi

