#!/bin/bash
songdata="$(echo -ne "status\ncurrentsong\nclose\n" | ncat -n -w 1 "$(dig +short mpd-host | tr -d '\n')" 8600 2>/dev/null))"
if [[ $? != 0 ]]; then
  exit
fi
thesong=$(echo "$songdata" | grep "file:" | cut -d ' ' -f2-)
regex="\-([A-Za-z0-9_-]{11})((\.[a-zA-Z0-9]+)?)\.(mp3|m4a)"
curmode=$(echo "$songdata" | grep "state:" | cut -d ' ' -f2-)
if [ "$curmode" = "play" ]; then
  mpc pause
fi
if [[ $thesong =~ $regex ]]; then
  # there is song id
  songcurrent=$(echo "$songdata" | grep "elapsed:" | cut -d ' ' -f2- | cut -d '.' -f1)
  chromium "https://www.youtube.com/watch?v=${BASH_REMATCH[1]}&t=$songcurrent" >/dev/null 2>&1 &
else
  # there is no song id so try our luck
  chromium "http://www.google.com/search?btnI=Search&q=youtube+$(
    echo "$thesong" | php -r "echo rawurlencode(file_get_contents(\"php://stdin\"));"
  )" >/dev/null 2>&1 &
fi

# go to chrome window
#~/dev/i3wmonarch/scripts/i3wm/activate_window.sh "Chromium"
