#!/usr/bin/env bash

export LANG=bg_BG.UTF-8

if command -v /usr/bin/thunderbird-beta &>/dev/null; then
  MY_MAIL_CLIENT_DEF="/usr/bin/thunderbird-beta"
else
  MY_MAIL_CLIENT_DEF="/usr/bin/thunderbird"
fi

my_client=${MY_MAIL_CLIENT:-${MY_MAIL_CLIENT_DEF}}

exec -- ${my_client} "$@"
