#!/usr/bin/env bash

set -e

pname="$(echo "$(basename "$0")" | sha1sum | cut -d ' ' -f1)"
echo "$pname"
myroot="/work/temp/chromium-homes/$pname"
mkdir -pv "$myroot"
export HOME="$myroot"
exec chromium
