#!/bin/bash

set -e

# check for tools
command -v maim > /dev/null 2>&1 || { echo "need maim!" 1>&2; exit 1; }

# @TODO: maybe use $XDG_CONFIG_HOME
[ -f "$(dirname "$0")/.screenshot" ] && source "$(dirname "$0")/.screenshot"

# target directory
TARGET_DIR=${TARGET_DIR:-$HOME/Pictures/Screenshots}

# filename generation command - not the safest way
filename="$(${NAME_CMD:-date +%Y_%m_%d_%H_%M_%S_%N})"

cmd=maim
mode=full

if [ ! -z "$1" ]; then
  cmd="maim -s -p 0 -c 0.96,0.5,0.09"
	mode="partial"
fi

# create screenshot
$cmd "${TARGET_DIR}/${filename}.png"
# load it into clipboard
cat "${TARGET_DIR}/${filename}.png" | xclip -in -selection clipboard -t image/png

if [ ! -z "$2" ]; then
    if [ ! -z "$UPLOAD_CMD" ]; then
        "$UPLOAD_CMD" "${TARGET_DIR}/${filename}.png"
        if [ ! -z "$UPLOAD_URL" ]; then
            echo "$UPLOAD_URL/${filename}.png" | xclip -in -selection clipboard
        fi
    fi
fi

NOTIFY=${SS_NOTIFY:-yes}
[[ "$NOTIFY" == "yes" ]] && notify-send "Screenshot $mode" "${TARGET_DIR}/${filename}.png"
