#!/bin/bash
case $BLOCK_BUTTON in
  1) ~/dev/i3wmonarch/github.com/nonpop/xkblayout-state/xkblayout-state set +1;;
  3) ~/dev/i3wmonarch/github.com/nonpop/xkblayout-state/xkblayout-state set -1;;
esac
kb="$(~/dev/i3wmonarch/github.com/nonpop/xkblayout-state/xkblayout-state print %s)"
echo $kb
echo $kb
