#!/bin/bash
# https://www.reddit.com/r/unixporn/comments/3358vu/i3lock_unixpornworthy_lock_screen

keepmusic=${1:-"0"}

# take screenshot and use it as background
icon="$HOME/.xlock/icon.png"
tmpbg='/tmp/screen.png'
scrot -o "$tmpbg"
convert "$tmpbg" -scale 20% -scale 500% "$tmpbg"
convert "$tmpbg" "$icon" -geometry +960+540 -composite -matte "$tmpbg"
convert "$tmpbg" "$icon" -geometry +2880+540 -composite -matte "$tmpbg"

# pause audioplayer and save state
if [ "$keepmusic" -eq 0 ]; then
    playerlaststate="$(~/dev/i3wmonarch/scripts/multimedia/getcurrentsongmpc | sed -n 1p | cut -d ' ' -f1)"
    ~/dev/i3wmonarch/scripts/multimedia/audioplayer_control pause
fi
# reset keyboard layout
~/dev/i3wmonarch/github.com/nonpop/xkblayout-state/xkblayout-state set 0

# kill all i3block instances while the pc is locked
#killall i3blocks

# turn off monitor(s)
sleep 1; xset dpms force off

# lock macbook
[ "$HOSTNAME" == "iliyan-work" ] \
  &&  /work/dev/bin/mac-lock.sh lock & 

# lock the screen
i3lock -i "$tmpbg" -n

# restart i3
#i3-msg restart

# unlock macbook
[ "$HOSTNAME" == "iliyan-work" ] \
  && /work/dev/bin/mac-lock.sh unlock &

# start playing again
if [ "$playerlaststate" = "" ]; then
    ~/dev/i3wmonarch/scripts/multimedia/audioplayer_control play
fi

